### ISSUE TITLE
how to using of php api tarccar how to install?

### ISSUE THREAD

**Issue by mahdi00021** [yodiyil/traccar-api-php#1]
how to using of php api tarccar how to install?

**Comment by jaimzj** [comment]
@mahdi00021 
1. Install Traccar
2. setup an apache/php or any preferred web-server
3. host the api files on the web-servers root directory.
4. change the configurations on the traccarAPI file.
and thats all, another thing possible is there are examples given, you can use them to understand on how to use these functions

**Comment by mahdi00021** [comment]
Very thank but how to i connect from PHP API to server java traccar 
Do I install java server ?
Or only PHP server ?

**Comment by jaimzj** [comment]
You install traccar  and ensure your traccar works.
then you follow my instructions on top until point 3.
and point 4 above that i shared is what you need to do for your api to communicate with your traccar.

**Comment by mahdi00021** [comment]
Yes but your instruction is for start server PHP 
But traccar is java Lang

**Comment by jaimzj** [comment]
So what is the problem if Traccar is in JAVA and this API Integration is in PHP?

What do you want to achieve?

Have you managed to install and run traccar?

**Comment by mahdi00021** [comment]
My problem is that I want that connect PHP API to java server
But how to ?

And another question is I how to change source java and run on server

**Comment by jaimzj** [comment]
You cant just connect random things to random other things.

You need to have a purpose for doing something, if you are researching on php integration for traccar. 

Then you have to share the right information on what you wish to acheive. and answer questions I asked above.

And most importantly you have ignored my steps I shared above.

**Comment by mahdi00021** [comment]
A question , this API for what is ?
I want that using of PHP instead js web

**Comment by jaimzj** [comment]
This API is for those who want to or have PHP based development or projects. And wants to connect to Traccar server of theirs.

**Comment by mahdi00021** [comment]
Thanks 
So I remove web js traccar after install PHP API?

**Comment by jaimzj** [comment]
I understand you have some communication difficulties. but the best I can still help you is by telling you to read my responses above.

You are repeating the same questions again which I have answered.

You do not need to remove anything, 

1. you install traccar on your server.
2. you setup seperate apache/web-server anything you want and put your PHP files there.
3. and most importantly do some research and read carefully!
