### ISSUE TITLE
Geofences

### ISSUE THREAD

**Issue by ghost** [yodiyil/traccar-api-php#10]
I want to ask what are the plans for the geofences, when they will be available, do you have an online demo available to see the operation?

Best regards

**Comment by jaimzj** [comment]
Geofence creation, update, and delete is already added. You can find them at the following link

https://github.com/gpsguru/traccar-api-php/blob/b3beb9e2b5f2aff0aa305a6ece543aaecccd9728/traccarApi.php#L154

As for online demo, at the moment I have not decided to upload them yet.

If you have specific questions, feel free to ask and I shall try to help wherever I can.

**Comment by ghost** [comment]
I understand, then I hope you upload the online version to see the operation, thank you very much for your prompt response

Best regards

**Comment by jaimzj** [comment]
Right now there is no plan to upload them.
