### ISSUE TITLE
sessionId in gps::devices method

### ISSUE THREAD

**Issue by Hamzha** [yodiyil/traccar-api-php#12]
I logged in using my credentials and I get the standard array in return with name, token and other attributes. Now i want  to get the devices using gps::devices($sessionId,$id) . Now what is sessionId in this method? Do i need to pass token in sessionId or something else?

**Comment by jaimzj** [comment]
This has already been discussed multiple times, you should look up examples we have shared for login.

**Comment by Hamzha** [comment]
@jaimzj thanks for ur humble response.
I'll look up to the relavent topic for sure.
