### ISSUE TITLE
How to setup a Websocket connection with cookie authentication

### ISSUE THREAD

**Issue by esdan7** [yodiyil/traccar-api-php#14]
Hi,

I am trying to setup a Web socket connection to get live updates after authenticating via the API above (with a session cookie) but I cannot get it to work.

There is example how to create the Web socket connection with token authentication [here](https://github.com/traccar/traccar-web/blob/master/web/simple/app.js), however I am not sure how to do it with a cookie created with this API.

Can anyone who has more experience on that advice please?

**Comment by nabadawa** [comment]
You can do it like this.

` 	var wsUri = 'wss://**yourURL**/api/socket';

	function init()
	{
		myWebSocket();
	}

	function myWebSocket()
	{
		websocket = new WebSocket(wsUri);
		websocket.onopen = function(evt) { onOpen(evt) };
		websocket.onclose = function(evt) { onClose(evt) };
		websocket.onmessage = function(evt) { onMessage(evt) };
		websocket.onerror = function(evt) { onError(evt) };
	}
 
	function onOpen(evt)
	{
                // Define what you want to do "onOpen" here
		console.log("Websocket Connected");
	}

	function onClose(evt)
	{
                // Define what you want to do "onClose" here
		console.log("Websocket Disconnected");
		
		setTimeout(function() {
			init();
		}, 10000);
	}


	function onMessage(evt)
	{
                // Define what you want to do "onMessage" here. This is where you will receive the responses
	       console.log("RESPONSE: " + evt.data);
	}

	function onError(evt)
	{
                // Define what you want to do "onError" here
	}

	window.addEventListener("load", init, false);
`

**Comment by jaimzj** [comment]
@nabadawa Your example or answer does not address the issue or question being asked. Please post response when you have accurate answer to the specifics being sought 

@esdan7 I am closing this ticket, based on the discussions we had over email with reference to CORS and session handling.
