### ISSUE TITLE
api-use example

### ISSUE THREAD

**Issue by vrmonitorit** [yodiyil/traccar-api-php#16]
Hello,

I am trying to get the traccar-api-php to work as an example as i am new to all of this.  Have downloaded all files in the folder.

Modified Host in traccarApi.php.

When i call api-use-example, i get

<b>Warning</b>:  Undefined variable $data in <b>C:\xampp\htdocs\TraccarApi\traccar-api-php-master (1)\traccar-api-php-master\traccarApi.php</b> on line <b>17</b><br />
<br />
<b>Warning</b>:  Undefined variable $sessionId in <b>C:\xampp\htdocs\TraccarApi\traccar-api-php-master (1)\traccar-api-php-master\traccarApi.php</b> on line <b>17</b><br />
400

Can you please help?

**Comment by jaimzj** [comment]
Please provide additional information. The warning message does not mean equate to not working.

**Comment by vrmonitorit** [comment]
Hello,

I am using the example provided and getting the error message on $data as mentioned above.

**Comment by chrysllercs** [comment]
add code

ini_set('display_errors','Off');
ini_set('error_reporting', E_ALL );
