### ISSUE TITLE
what to send as $cookie parameter for any function

### ISSUE THREAD

**Issue by meneva** [yodiyil/traccar-api-php#3]
Hello, I found your api very useful for traccar. But I am stuck at some points. As i have seen most of the function has a parameter $cookie. what value should we send as $cookie parameter for addDevice() function?
can u pls give an example for addDevice(**$cookie**, $name, $uniqueId, $phone, $model, $category, $attributes)
Does the cookie mean username or password or token ?

thanks in advance

**Comment by jaimzj** [comment]
When you login a user with the `login($email, $password)` it returns a cookie value.
example of the same can be found here [https://github.com/yodiyil/traccar-api-php/blob/master/web-examples/login.php#L13](url) and thats the parameter that you pass in the `$cookie` for each call

**Comment by meneva** [comment]
hello, thanks for your prompt reply. yes i am getting the cookie value after login which is: cookie:"JSESSIONID=1citq7rw0h8dm1lb6guflmceex"
shall i send the whole value including JSESSIONID or just "1citq7rw0h8dm1lb6guflmceex" ?

**Comment by jaimzj** [comment]
You need to send the whole value which will include JESSIONID=

**Comment by meneva** [comment]
Hello, i can successfully login with your API. but if i call the logout function it just give me the following error:
{"data":[{"apiResponseCode":204,"response":null}]} . The session is not closed.
my logout button's code is as follows:

`$.get("http://MY_SERVER/api/logout.php?cookie="+user_info.cookie, {headers: {"Authorization": "Basic " + btoa("test:test")}})
        .done(function (d) {
	      	console.log(d);
	      	window.localStorage.clear();
      	})`

I even tried to put the URL to browser and it just retrun me the apiResponseCode":204

thanks for your support

**Comment by jaimzj** [comment]
@meneva it did destroy the session right? the response is correct 204 for logout.
