### ISSUE TITLE
link/unlink objects

### ISSUE THREAD

**Issue by guerrab** [yodiyil/traccar-api-php#4]
hello,
what is the function that allows us to link/unlink objects { deviceId:8, geofenceId: 16 }
NB:api/permissions not working .

**Comment by jaimzj** [comment]
Hello,

I have added the function to take care of geofence mapping to device and removal of mapping on line 179 of the code. link below ( I haven't tested it but should work, let me know if it works for you)

https://github.com/yodiyil/traccar-api-php/blob/031c614e702447cc97c8c6a2560245c9d7a1ca86/traccarApi.php#L179
