### ISSUE TITLE
Geo-Fence

### ISSUE THREAD

**Issue by balasmeh** [yodiyil/traccar-api-php#8]
can you please update your files by adding the Geo-Fence ,Notifications & Events using php. thx

**Comment by jaimzj** [comment]
Sure, please be more specific on what you want for geo-fence, notifications and events? and I would be more than glad to add them

**Comment by balasmeh** [comment]
Thank you for reply, I want first that any user who login are able to create any geofence and safe it in the databse ,second then when the vehicle enter or leave that are can be send SMS / email to user. 

I hope you were able to understand my point, and you can please share to me your email address for contacting you in future .

Thank  you

**Comment by jaimzj** [comment]
I shall add the function to create and update geofence for sure.

However for notifications this feature already exist? what do you want from this php based api to be achieved?

**Comment by balasmeh** [comment]
Yes please if you can add that function to create and update the geofence 

Actually I have small database and website for gps Im suing it for college project that's why I want to add that feature,

**Comment by jaimzj** [comment]
Okay the geofence feature will be added tonight ! shall post an update once its done on here.

however for the notification via sms / email part you mentioned I am still not clear what you want me to do in the code here.

**Comment by balasmeh** [comment]
No issue, thank you so much, 

To make it clear I have one table for GPS device and I want when the GPS device enter the geofence area that user created it can send sms/email ,hint " the vehicle enter the area".

Thank you again

**Comment by jaimzj** [comment]
I understood what you meant by notification, but I dont understand what you are trying to explain to me about database table.

Notifications is already a feature available in traccar. what is it that you want from the API ?

**Comment by balasmeh** [comment]
It's OK no problem, I just right now want the function of geofence to create and update an area by user and save it. 
I will explain the other things after that. 

Thank you

**Comment by balasmeh** [comment]
Hello sir,

Have you update the geofence file? 

thank you

**Comment by jaimzj** [comment]
Expect an update soon, I am working on adding multiple updates together soon which will include your requested feature as well.

**Comment by balasmeh** [comment]
thank you, and im waiting your new updates .

**Comment by jaimzj** [comment]
@balasmeh Geofence, and relevant features have been updated and tested to be working as well.

The whole code is being re-written so you might notice a major change, as I am working on adding support for all features.
